version: '3'
services:
  python3:
    restart: always
    build: .
    command: python3 HappyHackingTools.py_2022/app.py
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt